version: "3.3"
services:
  nginx_gateway:
    image: doodle
    ports:
      - 80:8080
      - 443:8443
    environment:
      - SERVER_NAME=localhost
      - SERVE_FILES=yes
      - DISABLE_DEFAULT_SERVER=no
      - PROXY_REAL_IP=yes
      - AUTO_LETS_ENCRYPT=no
      - REDIRECT_HTTP_TO_HTTPS=no
      - USE_LIMIT_REQ=no
      - HTTP2=no
      - ALLOWED_METHODS=GET|POST|HEAD
      - FEATURE_POLICY=accelerometer 'none'; ambient-light-sensor 'none'; autoplay 'none'; camera 'none'; display-capture 'none'; document-domain 'none'; encrypted-media 'none'; fullscreen 'none'; geolocation 'none'; gyroscope 'none'; magnetometer 'none'; microphone 'none'; midi 'none'; payment 'none'; picture-in-picture 'none'; speaker 'none'; sync-xhr 'self'; usb 'none'; vibrate 'none'; vr 'none'
    volumes:
      - ./server-conf/conf.d:/server-confs:ro
      - ./neginx/certs:/etc/letsencrypt